# $schema=https://json.schemastore.org/lazygit.json
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --line-numbers
gui:
  theme:
    selectedLineBgColor:
      - '#333333'
